
# copied from GO's Make.inc
nullstring :=
space := $(nullstring) # a space at the end
QUOTED_GOROOT:=$(subst $(space),\ ,$(GOROOT))
pkgdir=$(QUOTED_GOROOT)/pkg/$(GOOS)_$(GOARCH)

    CC=$GOBIN/8g
    LD=$GOBIN/8l
    CEXT=.8

CFLAGS=-g -O3 -fomit-frame-pointer -fPIC
ifeq ($(GOARCH),386)
GOC=$(GOBIN)/8g
GOL=$(GOBIN)/8l
GOCEXT=8
CFLAGS+=-m32
else
GOC=$(GOBIN)/6g
GOL=$(GOBIN)/6l
GOCEXT=6
CFLAGS+=-m64
endif

EXT=
ifeq ($(GOOS),darwin)
CFLAGS+=-D__DARWIN__
LDFLAGS+=-dynamiclib -Wl,-undefined,dynamic_lookup
else ifeq ($(GOOS),freebsd)
CFLAGS+=-D__FREEBSD__
LDFLAGS+=-shared -lpthread -lm -Wl,-R,`pwd`
else ifeq ($(GOOS),linux)
CFLAGS+=-D__LINUX__
LDFLAGS+=-shared -lpthread -lm -Wl,-R,`pwd`
else ifeq ($(GOOS),windows)
EXT=.exe
CFLAGS+=-D__WINDOWS__
LDFLAGS+=-shared -lm -mthreads
else
$(error Invalid $$GOOS '$(GOOS)'; must be darwin, freebsd, linux, or windows)
endif


all:
	gcc $(CFLAGS) -c cpu.c

example:
	$(GOC) example.go
	$(GOL) -o example$(EXT) example.$(GOCEXT)


